# Generated by Django 6.0.7 on 2026-08-17 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspecciones', '0012_remove_fotoinspeccion_seccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_catalogo', models.CharField(db_index=True, help_text='Ej.: FA0201, FA0302, CV2401.', max_length=30)),
                ('area', models.CharField(default='420', max_length=30)),
                ('tag', models.CharField(db_index=True, max_length=80)),
                ('componente', models.CharField(max_length=150)),
                ('familia', models.CharField(db_index=True, max_length=50)),
                ('tecnica', models.CharField(blank=True, max_length=50)),
                ('codigo_reporte', models.CharField(blank=True, db_index=True, max_length=120)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_inspeccion', models.DateField(blank=True, null=True)),
                ('fecha_reporte', models.DateField(blank=True, null=True)),
                ('condicion_general', models.CharField(choices=[('NO_MEDIDO', 'No medido'), ('NORMAL', 'Normal'), ('PRECAUCION', 'Precaución'), ('TOLERABLE', 'Tolerable'), ('CRITICO', 'Crítico')], default='NO_MEDIDO', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('DEVUELTO', 'Devuelto'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado'), ('PUBLICADO', 'Publicado')], db_index=True, default='BORRADOR', max_length=20)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('mediciones', models.JSONField(blank=True, default=list)),
                ('comentario_revision', models.TextField(blank=True)),
                ('motivo_devolucion', models.TextField(blank=True)),
                ('fecha_envio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision_supervisor', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion_analista', models.DateTimeField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_filtros_analista', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_filtros_cliente', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_filtros_creados', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_filtros_inspector', to=settings.AUTH_USER_MODEL)),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_filtros', to='inspecciones.parada')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_filtros_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_programada', 'tag', 'codigo_catalogo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('DEVUELTO', 'Devuelto'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado'), ('PUBLICADO', 'Publicado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('DEVUELTO', 'Devuelto'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado'), ('PUBLICADO', 'Publicado')], max_length=20)),
                ('accion', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_estados_filtros', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='filtros_mm.reportefiltro')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FotoReporteFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(blank=True, max_length=100)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(upload_to='filtros_mm/%Y/%m/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='filtros_mm.reportefiltro')),
            ],
            options={
                'ordering': ['seccion', 'orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reportefiltro',
            constraint=models.UniqueConstraint(fields=('parada', 'codigo_catalogo'), name='uniq_reporte_filtro_parada_catalogo'),
        ),
    ]
