# Generated by Django 6.0.7 on 2026-07-30 16:37

import django.core.validators
import django.db.models.deletion
import inspecciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('tag', models.CharField(max_length=30, unique=True, verbose_name='TAG')),
                ('proceso', models.CharField(default='Chancado', max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faja',
                'verbose_name_plural': 'Fajas',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FAJA', 'Faja / Top Cover'), ('POLEAS', 'Poleas'), ('LIFE_SHAFT', 'Life Shaft')], max_length=20)),
                ('codigo_reporte', models.CharField(max_length=150, unique=True)),
                ('fecha_programada', models.DateField()),
                ('fecha_inspeccion', models.DateField(blank=True, null=True)),
                ('fecha_reporte', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('DEVUELTO', 'Devuelto al inspector'), ('REVISADO', 'Revisado por supervisor'), ('APROBADO', 'Aprobado por analista'), ('PUBLICADO', 'Publicado para cliente')], default='BORRADOR', max_length=30)),
                ('condicion_general', models.CharField(choices=[('NORMAL', 'Normal'), ('PRECAUCION', 'Precaución'), ('CRITICO', 'Crítico'), ('NO_MEDIDO', 'No medido')], default='NORMAL', max_length=20)),
                ('planta', models.CharField(default='Chancado', max_length=100)),
                ('proceso', models.CharField(default='Transporte de mineral', max_length=120)),
                ('etapa', models.CharField(default='Operaciones', max_length=100)),
                ('condicion_equipo', models.CharField(default='En uso', max_length=100)),
                ('circunstancias', models.TextField(blank=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('comentarios_revision', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_analizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_cliente', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('faja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones', to='inspecciones.faja')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones_supervisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
                'ordering': ['-fecha_programada', '-id'],
                'permissions': [('enviar_revision', 'Puede enviar inspecciones a revisión'), ('devolver_inspector', 'Puede devolver inspecciones al inspector'), ('revisar_inspeccion', 'Puede revisar inspecciones'), ('aprobar_inspeccion', 'Puede aprobar inspecciones'), ('publicar_inspeccion', 'Puede publicar inspecciones')],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('DEVUELTO', 'Devuelto al inspector'), ('REVISADO', 'Revisado por supervisor'), ('APROBADO', 'Aprobado por analista'), ('PUBLICADO', 'Publicado para cliente')], max_length=30)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to=settings.AUTH_USER_MODEL)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inspecciones.inspeccion')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FotoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=inspecciones.models.ruta_foto_inspeccion)),
                ('codigo_dano', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('subida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotografias_subidas', to=settings.AUTH_USER_MODEL)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='inspecciones.inspeccion')),
            ],
            options={
                'verbose_name': 'Fotografía',
                'verbose_name_plural': 'Fotografías',
                'ordering': ['creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=120)),
                ('punto', models.CharField(blank=True, max_length=50)),
                ('bastidor', models.CharField(blank=True, max_length=50)),
                ('lado', models.CharField(blank=True, max_length=50)),
                ('posicion', models.CharField(blank=True, max_length=80)),
                ('componente', models.CharField(blank=True, max_length=120)),
                ('espesor_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('b', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('c', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('e', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('f', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('desgaste', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_desgaste', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('porcentaje_residual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('condicion', models.CharField(choices=[('NORMAL', 'Normal'), ('PRECAUCION', 'Precaución'), ('CRITICO', 'Crítico'), ('NO_MEDIDO', 'No medido')], default='NORMAL', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_resumen', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='inspecciones.inspeccion')),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='inspeccion',
            constraint=models.UniqueConstraint(fields=('faja', 'tipo', 'fecha_programada'), name='inspeccion_unica_faja_tipo_fecha'),
        ),
    ]
