# Generated by Django 6.0.7 on 2026-08-02 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0002_poleas_lifeshaft'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionEmpalmeCVB0003',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=50)),
                ('empalme', models.CharField(max_length=20)),
                ('bastidor_lado', models.CharField(max_length=80)),
                ('posicion', models.CharField(max_length=20)),
                ('espesor_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('a', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('b', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('d', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('e', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('f', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empalmes_cvb0003', to='inspecciones.inspeccion')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicionTramoCVB0003',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARGA', 'Carga'), ('RETORNO', 'Retorno')], max_length=10)),
                ('tramo', models.CharField(max_length=60)),
                ('medicion', models.PositiveIntegerField()),
                ('bastidor', models.CharField(max_length=20)),
                ('espesor_nominal', models.DecimalField(decimal_places=2, default=19, max_digits=6)),
                ('a', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('b', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('d', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('e', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('f', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_cvb0003', to='inspecciones.inspeccion')),
            ],
            options={
                'ordering': ['tipo', 'orden', 'id'],
            },
        ),
    ]
