# Generated by Django 6.0.7 on 2026-08-02 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0003_medicionempalmecvb0003_mediciontramocvb0003'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoFajaCVB0003',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('EMPALMES', 'Empalmes'), ('CARGA', 'Tramos de carga'), ('RETORNO', 'Tramos de retorno')], max_length=20)),
                ('imagen', models.ImageField(upload_to='inspecciones/faja/cvb0003/')),
                ('codigo_dano', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias_cvb0003', to='inspecciones.inspeccion')),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_faja_cvb0003_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seccion', 'creada_en', 'id'],
            },
        ),
    ]
