# Generated by Django 6.0.7 on 2026-08-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0004_fotofajacvb0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='analista_elabora_nombre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Analista que elabora'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='analista_valida_nombre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Analista que valida'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='inspector_campo_nombre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Inspector de campo'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='supervisor_campo_nombre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Supervisor de campo'),
        ),
    ]
