# Generated by Django 6.0.7 on 2026-08-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0005_inspeccion_analista_elabora_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoinspeccion',
            name='seccion',
            field=models.CharField(choices=[('EMPALME_E01', 'Empalme E-01'), ('EMPALME_E02', 'Empalme E-02'), ('PUNTOS_MEDICION', 'Puntos de medición')], default='PUNTOS_MEDICION', max_length=30),
        ),
        migrations.AddField(
            model_name='fotoinspeccion',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
