# Generated by Django 6.0.7 on 2026-08-07 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0006_fotoinspeccion_seccion_fotoinspeccion_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeshaftinspeccion',
            name='tipo_medicion',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CAMPANA', 'Campaña (Inicio + Fin)')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='poleainspeccion',
            name='tipo_medicion',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CAMPANA', 'Campaña (Inicio + Fin)')], default='NORMAL', max_length=10),
        ),
        migrations.CreateModel(
            name='MedicionLifeShaftCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('INICIO', 'Inicio de campaña'), ('FIN', 'Fin de campaña')], max_length=10)),
                ('punto', models.PositiveSmallIntegerField()),
                ('ubicacion', models.CharField(default='PUNTOS SENTIDO RADIAL', max_length=100)),
                ('a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('b', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('c', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('e', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('f', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('life_shaft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_campana', to='inspecciones.lifeshaftinspeccion')),
            ],
            options={
                'ordering': ['fase', 'orden', 'punto'],
                'constraints': [models.UniqueConstraint(fields=('life_shaft', 'fase', 'punto'), name='punto_unico_lifeshaft_fase_campana')],
            },
        ),
        migrations.CreateModel(
            name='MedicionPoleaCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('INICIO', 'Inicio de campaña'), ('FIN', 'Fin de campaña')], max_length=10)),
                ('punto', models.PositiveSmallIntegerField()),
                ('posicion', models.CharField(blank=True, max_length=100)),
                ('a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('b', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('c', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('e', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('f', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('polea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_campana', to='inspecciones.poleainspeccion')),
            ],
            options={
                'ordering': ['fase', 'orden', 'punto'],
                'constraints': [models.UniqueConstraint(fields=('polea', 'fase', 'punto'), name='punto_unico_polea_fase_campana')],
            },
        ),
    ]
