# Generated by Django 6.0.7 on 2026-08-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0011_parada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoinspeccion',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='fotoinspeccion',
            name='titulo',
        ),
    ]
